import React, {useMemo, useState} from "react";
import {createRoot} from "react-dom/client";
import {
  Activity, AlertTriangle, ArrowRight, BarChart3, BatteryCharging, BrainCircuit,
  CheckCircle2, ChevronRight, CircleGauge, CloudSnow, Database, Fuel, Gauge,
  Globe2, Leaf, Lightbulb, LogOut, Menu, Moon, Play, Radar, RefreshCw,
  Settings, ShieldCheck, Sparkles, Thermometer, TrendingDown, TrendingUp, User,
  Wind, Zap, X, SlidersHorizontal, FileText
} from "lucide-react";
import {LineChart, Line, AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend} from "recharts";
import "./styles.css";

const navItems = [
  ["dashboard","Dashboard",Gauge],["data","Station Data Entry",Database],["monitoring","Energy Monitoring",Activity],["forecast","AI Forecast",BrainCircuit],
  ["renewable","Renewable Energy",Leaf],["storage","Storage",BatteryCharging],["fuel","Fuel Optimization",Fuel],
  ["recommendations","AI Recommendations",Lightbulb],["alerts","Alerts",AlertTriangle],["simulation","Simulation",SlidersHorizontal],
  ["analytics","Analytics",BarChart3],["reports","Reports",FileText]
];

const hours = ["00:00","04:00","08:00","12:00","16:00","20:00"];
const energyData = hours.map((h,i)=>({time:h,generation:[38,44,76,92,70,49][i],consumption:[48,51,59,64,71,57][i],battery:[71,68,74,82,76,69][i]}));
const forecastData = ["Now","+2h","+4h","+6h","+8h","+10h","+12h","+14h"].map((t,i)=>({time:t,actual:i<2?[64,67][i]:null,predicted:[64,67,70,73,78,75,69,61][i],renewable:[72,76,84,91,79,63,51,43][i]}));

function Brand(){return <div className="brand"><div className="brand-mark"><Globe2 size={21}/></div><span>PolarGrid</span></div>}

function Landing({onLogin}){
 return <div className="app">
  <header className="topbar"><div className="container" style={{display:"flex",width:"100%",alignItems:"center",justifyContent:"space-between"}}><Brand/><nav className="nav"><a href="#platform">Platform</a><a href="#capabilities">Capabilities</a><a href="#workflow">Workflow</a></nav><button className="btn primary" onClick={onLogin}>Open Dashboard <ArrowRight size={15} style={{verticalAlign:"middle"}}/></button></div></header>
  <main>
   <section className="hero"><div className="container">
    <div className="eyebrow">Energy intelligence for extreme environments</div>
    <h1>Make every unit of energy count.</h1>
    <p>PolarGrid brings forecasting, renewable integration, storage visibility and fuel optimization into one decision-support workspace for polar research station operations.</p>
    <div className="hero-actions"><button className="btn primary" onClick={onLogin}>Explore the station dashboard <ArrowRight size={15}/></button><a className="btn ghost" href="#capabilities">See capabilities</a></div>
    <div className="grid3" style={{marginTop:55}}>
      <div className="card"><div className="eyebrow">01</div><h3>Forecast</h3><p style={{color:"var(--muted)",lineHeight:1.6,fontSize:13}}>Anticipate demand and renewable availability before the next operating window.</p></div>
      <div className="card"><div className="eyebrow">02</div><h3>Optimize</h3><p style={{color:"var(--muted)",lineHeight:1.6,fontSize:13}}>Balance load, storage and backup requirements with clear recommendations.</p></div>
      <div className="card"><div className="eyebrow">03</div><h3>Act</h3><p style={{color:"var(--muted)",lineHeight:1.6,fontSize:13}}>Give station teams one calm, information-rich view of energy risk.</p></div>
    </div>
   </div></section>
   <section className="section" id="capabilities"><div className="container"><div className="eyebrow">Platform capabilities</div><h2>One operating picture, several decisions.</h2><p className="section-lead">Designed around the Station Energy Manager and operations team, with supporting views for administrators and research personnel.</p>
    <div className="grid3" style={{marginTop:28}}>
      {[[Zap,"Energy monitoring","Track generation, demand, storage and balance."],[BrainCircuit,"AI forecasting","Estimate upcoming load and renewable contribution."],[Fuel,"Fuel optimization","Plan backup use around predicted energy gaps."],[AlertTriangle,"Anomaly detection","Surface unusual demand or generation behavior."],[SlidersHorizontal,"Scenario simulation","Test changing demand, renewable and reserve assumptions."],[FileText,"Reports & analytics","Turn station energy history into operational summaries."]].map(([I,t,d])=><div className="card feature-card" key={t}><div className="iconbox"><I size={20}/></div><h3>{t}</h3><p>{d}</p></div>)}
    </div>
   </div></section>
   <section className="section" id="workflow"><div className="container"><div className="grid2"><div><div className="eyebrow">Decision loop</div><h2>From raw signals to a practical next step.</h2><p className="section-lead">The prototype keeps humans in control. It detects patterns, forecasts likely conditions and explains recommended actions instead of directly controlling critical infrastructure.</p></div><div className="card">
    {["Station & environmental data","Data validation and storage","AI forecasting + anomaly detection","Energy and fuel optimization","Dashboard, alerts and recommendations"].map((x,i)=><div key={x} style={{display:"flex",gap:12,alignItems:"center",padding:"12px 0",borderBottom:i<4?"1px solid #173045":"none"}}><span className="avatar" style={{width:28,height:28,fontSize:10}}>{i+1}</span><span style={{fontSize:12,color:"#c4d1da"}}>{x}</span><ChevronRight size={14} color="#5f778b" style={{marginLeft:"auto"}}/></div>)}
   </div></div></div></section>
  </main>
  <footer className="footer"><div className="container footer-inner"><span>PolarGrid • Energy intelligence for polar research operations</span><span>Decision support, not autonomous infrastructure control.</span></div></footer>
 </div>
}

function Login({onLogin,onBack}){
 const [email,setEmail]=useState("manager@polargrid.demo"),[password,setPassword]=useState("PolarGrid123"),[err,setErr]=useState("");
 const submit=e=>{e.preventDefault(); if(password==="PolarGrid123" && ["manager@polargrid.demo","admin@polargrid.demo","operations@polargrid.demo"].includes(email.toLowerCase())) onLogin(email); else setErr("Use one of the demo accounts shown below.");};
 return <div className="login-page"><div className="card login-card"><button className="btn ghost small" onClick={onBack}>← Back</button><div style={{marginTop:25}}><Brand/><h1>Station workspace</h1><p>Sign in to view the energy intelligence dashboard.</p></div><form onSubmit={submit}><div className="field"><label>EMAIL</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></div><div className="field"><label>PASSWORD</label><input value={password} onChange={e=>setPassword(e.target.value)} type="password"/></div>{err&&<div className="error">{err}</div>}<button className="btn primary" style={{width:"100%",marginTop:15}}>Sign in <ArrowRight size={15} style={{verticalAlign:"middle"}}/></button></form><div className="demo-box"><b>Demo accounts</b><br/>Manager: manager@polargrid.demo<br/>Admin: admin@polargrid.demo<br/>Operations: operations@polargrid.demo<br/>Password: PolarGrid123</div></div></div>
}

function Sidebar({page,setPage,open,setOpen,onLogout}){
 return <aside className={"sidebar "+(open?"open":"")}><div className="brand"><div className="brand-mark"><Globe2 size={21}/></div><span>PolarGrid</span>{open&&<button onClick={()=>setOpen(false)} style={{marginLeft:"auto",background:"none",border:0,color:"#9fb3c3"}}><X size={18}/></button>}</div><div className="side-label">Workspace</div>{navItems.map(([id,label,I])=><button className={"side-link "+(page===id?"active":"")} key={id} onClick={()=>{setPage(id);setOpen(false)}}><I size={15}/>{label}</button>)}<div className="side-bottom"><button className="side-link"><Settings size={15}/>Settings</button><button className="side-link" onClick={onLogout}><LogOut size={15}/>Sign out</button></div></aside>
}

const DEMO_STATION={
  stationName:"Aurora Research Station", region:"Polar Region", currentGeneration:82, currentConsumption:64,
  solarGeneration:45, windGeneration:37, batteryCapacity:500, batterySoc:78,
  fuelAvailable:680, tankCapacity:1000, temperature:-24, windSpeed:18,
  forecastDemand:720, forecastRenewable:850, criticalLoad:40
};

function derive(d){
 const generation=Number(d.currentGeneration)||0, consumption=Number(d.currentConsumption)||0;
 const fuelPct=d.tankCapacity>0 ? Math.max(0,Math.min(100,(d.fuelAvailable/d.tankCapacity)*100)) : 0;
 const renewableShare=consumption>0 ? Math.min(100,(generation/consumption)*100) : 0;
 const gap=Math.max(0,consumption-generation);
 const dailyGap=Math.max(0,(d.forecastDemand||0)-(d.forecastRenewable||0));
 const backupLiters=Math.round(dailyGap*0.055 + gap*1.2);
 const daysFuel=backupLiters>0 ? (d.fuelAvailable/backupLiters).toFixed(1) : "∞";
 const batteryKwh=Math.round((d.batteryCapacity||0)*(d.batterySoc||0)/100);
 const renewableIndex=Math.max(0,Math.min(100,Math.round(renewableShare*0.65 + (d.windSpeed||0)*1.1 + Math.max(0,35-(d.temperature||0))*0.15)));
 return {generation,consumption,fuelPct,renewableShare,gap,dailyGap,backupLiters,daysFuel,batteryKwh,renewableIndex,forecastDemand:Number(d.forecastDemand)||0,forecastRenewable:Number(d.forecastRenewable)||0,batterySoc:Number(d.batterySoc)||0};
}

function StationData({data,onRun,onDemo}){
 const [form,setForm]=useState(data);
 const update=(key,value)=>setForm(f=>({...f,[key]:value}));
 const submit=e=>{e.preventDefault();onRun({...form,currentGeneration:Number(form.solarGeneration)+Number(form.windGeneration),fuelAvailable:Number(form.fuelAvailable),batterySoc:Number(form.batterySoc)});};
 const Field=({label,name,type="number",suffix,step="1"})=><div className="field"><label>{label}{suffix&&<span style={{float:"right",color:"#5f778b"}}>{suffix}</span>}</label><input type={type} step={step} value={form[name]} onChange={e=>update(name,type==="number"?e.target.value:e.target.value)}/></div>;
 return <Page title="Station Data Entry" sub="Enter or update station and environmental parameters, then run the analysis to refresh every decision-support view.">
  <form onSubmit={submit}>
   <div className="card" style={{marginBottom:16}}><div className="card-title"><div><h3>Station profile</h3><p>These details identify the operating context used by the analysis.</p></div><Database size={18} color="#69e7f5"/></div><div className="grid2"><div className="field"><label>STATION NAME</label><input value={form.stationName} onChange={e=>update("stationName",e.target.value)}/></div><div className="field"><label>REGION</label><input value={form.region} onChange={e=>update("region",e.target.value)}/></div></div></div>
   <div className="grid2">
    <div className="card"><div className="card-title"><div><h3>Energy inputs</h3><p>Current generation and station demand.</p></div><Zap size={18} color="#69e7f5"/></div><div className="grid2"><Field label="SOLAR GENERATION" name="solarGeneration" suffix="kW"/><Field label="WIND GENERATION" name="windGeneration" suffix="kW"/><Field label="CURRENT DEMAND" name="currentConsumption" suffix="kW"/><Field label="CRITICAL LOAD" name="criticalLoad" suffix="kW"/></div><div className="callout">Current generation is calculated automatically as <b>solar + wind</b>.</div></div>
    <div className="card"><div className="card-title"><div><h3>Battery & fuel</h3><p>Reserve and backup-resource inputs.</p></div><BatteryCharging size={18} color="#54d89b"/></div><div className="grid2"><Field label="BATTERY CAPACITY" name="batteryCapacity" suffix="kWh"/><Field label="BATTERY SOC" name="batterySoc" suffix="%"/><Field label="FUEL AVAILABLE" name="fuelAvailable" suffix="L"/><Field label="TANK CAPACITY" name="tankCapacity" suffix="L"/></div></div>
   </div>
   <div className="grid2" style={{marginTop:16}}>
    <div className="card"><div className="card-title"><div><h3>Polar environment</h3><p>Environmental context for forecasting and renewable analysis.</p></div><CloudSnow size={18} color="#69e7f5"/></div><div className="grid2"><Field label="TEMPERATURE" name="temperature" suffix="°C"/><Field label="WIND SPEED" name="windSpeed" suffix="km/h"/></div></div>
    <div className="card"><div className="card-title"><div><h3>Forecast inputs</h3><p>Expected next-period demand and renewable generation.</p></div><BrainCircuit size={18} color="#f4c56b"/></div><div className="grid2"><Field label="FORECAST DEMAND" name="forecastDemand" suffix="kWh/day"/><Field label="FORECAST RENEWABLE" name="forecastRenewable" suffix="kWh/day"/></div></div>
   </div>
   <div className="card" style={{marginTop:16}}><div className="card-title"><div><h3>Run analysis</h3><p>Results remain based on the last submitted dataset until you run the analysis again.</p></div><Sparkles size={18} color="#69e7f5"/></div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button className="btn primary" type="submit"><Play size={15}/> Run AI Analysis</button><button className="btn" type="button" onClick={()=>{setForm(DEMO_STATION);onDemo();}}>Use Demo Data</button></div></div>
  </form>
 </Page>
}

function Metric({icon:Icon,label,value,sub,kind="cyan"}){return <div className="card metric"><div className="metric-head"><span>{label}</span><Icon size={16} className={kind}/></div><div className="metric-value">{value}</div><div className={"metric-sub "+kind}>{sub}</div></div>}

function Alerts({compact=false,a}){
 const alerts=[];
 if(a.gap>0) alerts.push(["danger","Energy gap detected",`Current demand exceeds renewable generation by ${a.gap} kW. Review flexible loads and reserve.` ,"High"]);
 if(a.batterySoc<66) alerts.push(["warning","Battery reserve",`Battery state of charge is ${a.batterySoc}%, below the configured review threshold.` ,"Medium"]);
 if(a.fuelPct<40) alerts.push(["danger","Fuel reserve",`Backup fuel is at ${a.fuelPct.toFixed(0)}%, below the reserve threshold.` ,"High"]);
 if(a.forecastDemand>a.forecastRenewable) alerts.push(["warning","Forecasted energy gap",`Forecast demand exceeds renewable availability by ${Math.round(a.forecastDemand-a.forecastRenewable)} kWh/day.` ,"Medium"]);
 if(!alerts.length) alerts.push(["positive","Renewable window","Current inputs indicate enough renewable generation to cover current demand.","Info"]);
 return <div>{alerts.slice(0,compact?2:4).map(([kind,t,d,s])=><div className="alert" key={t}><div className="alert-top"><span className={"severity "+kind}>{s}</span><span style={{fontSize:10,color:"#6d8597"}}>Active</span></div><h4>{t}</h4><p>{d}</p></div>)}</div>
}

function DashboardHome({d,a}){
 const chart=hours.map((h,i)=>({time:h,generation:Math.max(0,Math.round(d.generation*[.48,.58,.82,1.08,.86,.62][i])),consumption:Math.max(0,Math.round(d.consumption*[.75,.82,.92,1,1.1,.9][i]))}));
 return <><div className="page-title"><div><div className="eyebrow">Station overview</div><h1>Good evening, Station Operations</h1><p>{d.stationName} • {d.region} • Results from latest submitted dataset</p></div><span className={a.gap>0?"status danger":"status"}><i className="dot"/>{a.gap>0?"Review energy gap":"System stable"}</span></div>
 <div className="metric-grid"><Metric icon={Zap} label="Current generation" value={`${a.generation} kW`} sub={`${a.renewableShare.toFixed(0)}% of current demand`} kind="positive"/><Metric icon={Activity} label="Current consumption" value={`${a.consumption} kW`} sub={a.gap?`${a.gap} kW above renewable output`:`${a.generation-a.consumption} kW surplus`} kind="cyan"/><Metric icon={BatteryCharging} label="Battery reserve" value={`${d.batterySoc}%`} sub={`${a.batteryKwh} kWh estimated stored energy`} kind="positive"/><Metric icon={Fuel} label="Backup fuel" value={`${a.fuelPct.toFixed(0)}%`} sub={`${d.fuelAvailable} L available`} kind="warning"/></div>
 <div className="dashboard-grid"><div className="card chart-card"><div className="card-title"><div><h3>Energy balance</h3><p>Generation and station demand from the submitted inputs</p></div><div className="legend"><span><i style={{background:"#69e7f5"}}/>Generation</span><span><i style={{background:"#54d89b"}}/>Consumption</span></div></div><ResponsiveContainer width="100%" height={260}><AreaChart data={chart}><defs><linearGradient id="g1" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#69e7f5" stopOpacity=".3"/><stop offset="100%" stopColor="#69e7f5" stopOpacity="0"/></linearGradient></defs><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="time"/><YAxis/><Tooltip/><Area type="monotone" dataKey="generation" stroke="#69e7f5" fill="url(#g1)" strokeWidth={2}/><Line type="monotone" dataKey="consumption" stroke="#54d89b" strokeWidth={2} dot={false}/></AreaChart></ResponsiveContainer></div>
 <div className="card"><div className="card-title"><div><h3>Station conditions</h3><p>Environmental context</p></div><CloudSnow size={17} color="#69e7f5"/></div><div className="kpi-line"><span>Temperature</span><b>{d.temperature}°C</b></div><div className="progress"><span style={{width:`${Math.min(100,Math.max(8,Math.abs(d.temperature)*2))}%`}}/></div><div className="kpi-line"><span>Wind</span><b>{d.windSpeed} km/h</b></div><div className="progress"><span style={{width:`${Math.min(100,d.windSpeed*2)}%`}}/></div><div className="kpi-line"><span>Renewable index</span><b>{a.renewableIndex} / 100</b></div><div className="progress"><span style={{width:`${a.renewableIndex}%`}}/></div><div className="callout" style={{marginTop:18}}><Wind size={14} style={{verticalAlign:"middle",marginRight:6}}/> {a.renewableIndex<55?"Environmental conditions may reduce renewable contribution in the next operating period.":"Environmental inputs currently support the renewable generation profile."}</div></div></div>
 <div className="dashboard-grid"><div className="card"><div className="card-title"><div><h3>AI recommendations</h3><p>Generated from the submitted station dataset</p></div><BrainCircuit size={17} color="#69e7f5"/></div><Recommendations compact a={a} d={d}/></div><div className="card"><div className="card-title"><div><h3>Priority alerts</h3><p>Requires operator attention</p></div><AlertTriangle size={17} color="#f4c56b"/></div><Alerts compact a={a}/></div></div></>;
}

function Recommendations({compact=false,a,d}){
 const list=[];
 if(a.gap>0) list.push(["Shift non-critical loads",`Current demand is ${a.gap} kW above renewable generation. Move flexible loads into renewable windows.`,`${a.gap} kW`,`High`]);
 else list.push(["Use renewable surplus",`Current renewable generation provides ${Math.max(0,a.generation-a.consumption)} kW of surplus for storage or flexible loads.`,`${Math.max(0,a.generation-a.consumption)} kW`,`Medium`]);
 list.push(["Protect battery reserve",`Maintain the battery above the configured reserve while the forecast is reviewed.`,`${d.batterySoc}% SOC`,`Medium`]);
 if(d.forecastDemand>d.forecastRenewable) list.push(["Review backup schedule",`Forecast demand exceeds renewable availability by ${Math.round(d.forecastDemand-d.forecastRenewable)} kWh/day.`,`${a.backupLiters} L`,`High`]);
 else list.push(["Plan renewable-first operation",`Forecast renewable availability covers the expected daily demand profile.`,`+${Math.round(d.forecastRenewable-d.forecastDemand)} kWh`,`Low`]);
 return <div>{list.slice(0,compact?3:list.length).map(([t,desc,impact,p])=><div className="recommend" key={t}><Lightbulb size={16}/><div style={{flex:1}}><h4>{t} <span style={{float:"right",fontSize:9,color:p==="High"?"#ff8b98":"#f4c56b"}}>{p}</span></h4><p>{desc}</p><div style={{fontSize:10,color:"#69e7f5",marginTop:5}}>Potential impact: {impact}</div></div></div>)}</div>
}

function Monitoring({d,a}){return <Page title="Energy Monitoring" sub="Observe generation, demand and storage behavior across the station."><div className="metric-grid"><Metric icon={Zap} label="Generation" value={`${a.generation} kW`} sub={`Solar ${d.solarGeneration} + wind ${d.windGeneration}`} kind="positive"/><Metric icon={Activity} label="Load" value={`${a.consumption} kW`} sub="Current station demand"/><Metric icon={BatteryCharging} label="Battery flow" value={`${Math.abs(a.gap)} kW`} sub={a.gap?"Discharging / backup support":"Charging opportunity"} kind={a.gap?"warning":"positive"}/><Metric icon={CircleGauge} label="Balance" value={`${a.generation-a.consumption>0?"+":""}${a.generation-a.consumption} kW`} sub={a.gap?"Deficit":"Surplus"} kind={a.gap?"warning":"positive"}/></div><div className="card" style={{marginTop:16}}><div className="card-title"><div><h3>Generation vs consumption</h3><p>Current input profile</p></div></div><ResponsiveContainer width="100%" height={350}><LineChart data={hours.map((h,i)=>({time:h,generation:Math.round(a.generation*[.5,.65,.85,1.08,.9,.6][i]),consumption:Math.round(a.consumption*[.75,.82,.92,1,1.1,.9][i]),battery:Math.max(0,d.batterySoc-(i*2))}))}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="time"/><YAxis/><Tooltip/><Legend/><Line type="monotone" dataKey="generation" stroke="#69e7f5" strokeWidth={3}/><Line type="monotone" dataKey="consumption" stroke="#54d89b" strokeWidth={3}/><Line type="monotone" dataKey="battery" stroke="#f4c56b" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div><div className="grid3" style={{marginTop:16}}><div className="card"><h3 style={{fontSize:14}}>Energy balance</h3><p style={{color:"#8da4b5",fontSize:12}}>{a.gap?"Current demand exceeds renewable output; backup support may be required.":"Current renewable output is available for storage or flexible loads."}</p><div className="progress"><span style={{width:`${Math.min(100,a.generation/a.consumption*100)}%`}}/></div></div><div className="card"><h3 style={{fontSize:14}}>Peak load</h3><p style={{color:"#8da4b5",fontSize:12}}>Projected peak from current operating profile.</p><b style={{fontSize:22}}>{Math.round(a.consumption*1.12)} kW</b></div><div className="card"><h3 style={{fontSize:14}}>Data quality</h3><p style={{color:"#8da4b5",fontSize:12}}>Manual station dataset submitted successfully.</p><b className="positive">100%</b></div></div></Page>}

function Forecast({d,a}){const fd=["Now","+2h","+4h","+6h","+8h","+10h","+12h","+14h"].map((t,i)=>({time:t,actual:i<2?[a.consumption,Math.round(a.consumption*1.04)][i]:null,predicted:Math.round(a.consumption*[1,1.04,1.1,1.14,1.22,1.17,1.08,.96][i]),renewable:Math.round((d.forecastRenewable/24)*[.75,.84,.94,1.05,1.12,.98,.82,.7][i])}));const peak=Math.round(a.consumption*1.22);return <Page title="AI Forecast" sub="Forecasted station demand and renewable contribution for planning."><div className="card" style={{marginBottom:16}}><div className="card-title"><div><h3>Demand forecast</h3><p>Illustrative model output using the submitted station inputs and environmental context</p></div><span className="status"><i className="dot"/>Model ready</span></div><ResponsiveContainer width="100%" height={360}><LineChart data={fd}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="time"/><YAxis/><Tooltip/><Legend/><Line type="monotone" dataKey="actual" stroke="#69e7f5" strokeWidth={3} connectNulls/><Line type="monotone" dataKey="predicted" stroke="#f4c56b" strokeWidth={3} strokeDasharray="7 5"/><Line type="monotone" dataKey="renewable" stroke="#54d89b" strokeWidth={2}/></LineChart></ResponsiveContainer></div><div className="grid3"><div className="card"><div className="eyebrow">Next 6 hours</div><h2 style={{margin:"9px 0"}}>{Math.round(a.consumption*1.09)} kW</h2><p style={{color:"#8fa5b6",fontSize:12}}>Expected average demand</p></div><div className="card"><div className="eyebrow">Peak window</div><h2 style={{margin:"9px 0"}}>+6h</h2><p style={{color:"#8fa5b6",fontSize:12}}>Projected peak around {peak} kW</p></div><div className="card"><div className="eyebrow">Confidence</div><h2 style={{margin:"9px 0"}}>91%</h2><p style={{color:"#8fa5b6",fontSize:12}}>Illustrative confidence indicator</p></div></div></Page>}

function Renewable({d,a}){const share=Math.min(100,a.renewableShare);return <Page title="Renewable Energy" sub="Track renewable contribution and the environmental factors that influence it."><div className="grid3"><div className="card"><div className="card-title"><h3>Renewable contribution</h3><Leaf size={18} color="#54d89b"/></div><div style={{fontSize:38,fontWeight:800}}>{share.toFixed(0)}%</div><p style={{color:"#8298a9",fontSize:12}}>of current station demand is covered by renewable generation.</p><div className="progress"><span style={{width:`${share}%`}}/></div></div><div className="card"><div className="card-title"><h3>Weather context</h3><Thermometer size={18} color="#69e7f5"/></div><h2>{d.temperature}°C</h2><p style={{color:"#8298a9",fontSize:12}}>Polar conditions • Wind {d.windSpeed} km/h</p><div className="callout">Environmental inputs are used as context for the forecast and recommendation layer.</div></div><div className="card"><div className="card-title"><h3>Renewable forecast</h3><TrendingUp size={18} color="#54d89b"/></div><h2>{Math.round(d.forecastRenewable/24)} kW avg</h2><p style={{color:"#8298a9",fontSize:12}}>Average renewable availability implied by the submitted daily forecast.</p></div></div><div className="card" style={{marginTop:16}}><div className="card-title"><h3>Generation profile</h3></div><ResponsiveContainer width="100%" height={300}><AreaChart data={[0,1,2,3,4,5,6,7].map((i)=>({time:`+${i*2}h`,renewable:Math.round((d.forecastRenewable/24)*[.75,.84,.94,1.05,1.12,.98,.82,.7][i])}))}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="time"/><YAxis/><Tooltip/><Area dataKey="renewable" type="monotone" stroke="#54d89b" fill="#54d89b" fillOpacity=".12"/></AreaChart></ResponsiveContainer></div></Page>}

function Storage({d,a}){const stored=a.batteryKwh;return <Page title="Storage" sub="Understand battery state, reserve margin and charging opportunities."><div className="grid2"><div className="card"><div className="card-title"><div><h3>Battery state of charge</h3><p>Current reserve</p></div><BatteryCharging color="#69e7f5"/></div><div style={{fontSize:60,fontWeight:800,margin:"10px 0"}}>{d.batterySoc}%</div><div className="progress"><span style={{width:`${d.batterySoc}%`}}/></div><p style={{color:"#8298a9",fontSize:12}}>{stored} kWh estimated stored energy of {d.batteryCapacity} kWh capacity.</p></div><div className="card"><div className="card-title"><h3>Reserve guidance</h3><ShieldCheck size={18} color="#54d89b"/></div><div className="kpi-line"><span>Configured review threshold</span><b>66%</b></div><div className="kpi-line"><span>Current reserve</span><b>{d.batterySoc}%</b></div><div className="kpi-line"><span>Critical load</span><b>{d.criticalLoad} kW</b></div><div className="callout" style={{marginTop:18}}>{d.batterySoc<66?"Reserve is below the review threshold. Consider protecting storage before flexible loads are scheduled.":"Reserve is above the review threshold under the current submitted conditions."}</div></div></div><div className="card" style={{marginTop:16}}><div className="card-title"><h3>Storage outlook</h3></div><ResponsiveContainer width="100%" height={300}><AreaChart data={hours.map((h,i)=>({time:h,battery:Math.max(0,Math.min(100,d.batterySoc+(a.generation-a.consumption)*[0,.04,.08,.1,.06,.02][i]))}))}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="time"/><YAxis domain={[0,100]}/><Tooltip/><Area dataKey="battery" type="monotone" stroke="#f4c56b" fill="#f4c56b" fillOpacity=".12"/></AreaChart></ResponsiveContainer></div></Page>}

function FuelOptimization({d,a}){return <Page title="Fuel Optimization" sub="Plan backup fuel use around forecasted energy gaps and reserve constraints."><div className="grid3"><div className="card"><div className="eyebrow">Current level</div><div style={{fontSize:40,fontWeight:800,margin:"8px 0"}}>{a.fuelPct.toFixed(0)}%</div><div className="progress"><span style={{width:`${a.fuelPct}%`}}/></div><p style={{fontSize:11,color:"#8298a9"}}>{a.daysFuel} days estimated at the modeled backup requirement.</p></div><div className="card"><div className="eyebrow">Predicted use</div><div style={{fontSize:40,fontWeight:800,margin:"8px 0"}}>{a.backupLiters} L</div><p style={{fontSize:11,color:"#8298a9"}}>Estimated backup requirement from the submitted forecast and current energy gap.</p></div><div className="card"><div className="eyebrow">Optimization opportunity</div><div style={{fontSize:40,fontWeight:800,margin:"8px 0"}}>{Math.max(0,Math.round(a.backupLiters*.35))} L</div><p style={{fontSize:11,color:"#8298a9"}}>Illustrative avoidable use if flexible loads are shifted into renewable windows.</p></div></div><div className="card" style={{marginTop:16}}><div className="card-title"><h3>Backup requirement outlook</h3><Fuel size={18} color="#f4c56b"/></div><ResponsiveContainer width="100%" height={300}><BarChart data={[{day:"Today",fuel:Math.round(a.backupLiters*.9)},{day:"Tomorrow",fuel:a.backupLiters},{day:"D+2",fuel:Math.round(a.backupLiters*1.15)},{day:"D+3",fuel:Math.round(a.backupLiters*1.08)},{day:"D+4",fuel:Math.round(a.backupLiters*.9)},{day:"D+5",fuel:Math.round(a.backupLiters*.82)}]}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day"/><YAxis/><Tooltip/><Bar dataKey="fuel" fill="#f4c56b" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Page>}

function RecommendationsPage({d,a}){return <Page title="AI Recommendations" sub="Actionable suggestions generated from the current station state."><div className="card"><Recommendations a={a} d={d}/></div><div className="card" style={{marginTop:16}}><div className="card-title"><h3>How recommendations are formed</h3><BrainCircuit size={18} color="#69e7f5"/></div><div className="grid3">{["Current energy balance","Forecasted demand + renewable output","Battery reserve and backup constraints"].map((x,i)=><div className="callout" key={x}><b>{i+1}.</b> {x}</div>)}</div></div></Page>}

function AlertsPage({d,a}){return <Page title="Alerts" sub="Monitor operational signals that may require review."><div className="grid2"><div><Alerts a={a}/></div><div className="card"><div className="card-title"><h3>Alert policy</h3><Settings size={17}/></div>{[["Reserve threshold","66%"],["High demand threshold",`${Math.round(a.consumption*1.17)} kW`],["Renewable drop threshold","20%"],["Fuel reserve threshold","40%"]].map(x=><div className="kpi-line" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}<div className="callout" style={{marginTop:12}}>These thresholds are demonstration settings and can be connected to station policy in a production deployment.</div></div></div></Page>}

function Simulation({d,a}){const [renewable,setRenewable]=useState(100),[demand,setDemand]=useState(100),[battery,setBattery]=useState(d.batterySoc);const gen=Math.round(a.generation*renewable/100),load=Math.round(a.consumption*demand/100),reserve=Math.max(0,Math.min(100,Math.round(battery-(load-gen)*0.42))),deficit=Math.max(0,load-gen),fuel=Math.round(deficit*1.45);return <Page title="Scenario Simulation" sub="Explore how changes in generation, demand and reserve assumptions can affect station energy balance."><div className="simulator"><div className="card"><div className="card-title"><h3>Scenario controls</h3><RefreshCw size={17} color="#69e7f5"/></div><label className="kpi-line"><span>Renewable generation</span><b>{renewable}%</b></label><input className="slider" type="range" min="50" max="130" value={renewable} onChange={e=>setRenewable(+e.target.value)}/><label className="kpi-line"><span>Energy demand</span><b>{demand}%</b></label><input className="slider" type="range" min="60" max="150" value={demand} onChange={e=>setDemand(+e.target.value)}/><label className="kpi-line"><span>Starting battery reserve</span><b>{battery}%</b></label><input className="slider" type="range" min="20" max="100" value={battery} onChange={e=>setBattery(+e.target.value)}/><div className="callout" style={{marginTop:20}}><Sparkles size={14} style={{verticalAlign:"middle",marginRight:6}}/> Simulation starts from the latest submitted station dataset.</div></div><div className="card"><div className="card-title"><div><h3>Scenario outcome</h3><p>Illustrative decision-support calculation</p></div><span className={deficit>0?"status danger":"status"}><i className="dot"/>{deficit>0?"Backup risk":"Balanced"}</span></div><div className="scenario-output"><div className="scenario-stat"><span>Generation</span><strong>{gen} kW</strong></div><div className="scenario-stat"><span>Demand</span><strong>{load} kW</strong></div><div className="scenario-stat"><span>Energy gap</span><strong>{deficit} kW</strong></div><div className="scenario-stat"><span>Battery outlook</span><strong>{reserve}%</strong></div><div className="scenario-stat"><span>Fuel estimate</span><strong>{fuel} L</strong></div><div className="scenario-stat"><span>Reserve status</span><strong className={reserve<55?"warning":"positive"}>{reserve<55?"Watch":"Stable"}</strong></div></div><div className="callout" style={{marginTop:18}}>{deficit>0?"Consider shifting flexible loads and preserving battery reserve before scheduling backup generation.":"Current scenario maintains a positive energy balance. Flexible loads can be aligned with the renewable window."}</div></div></div></Page>}

function Analytics({d,a}){const monthly=[{m:"Jan",use:Math.round(d.currentConsumption*16),renew:Math.round(d.currentGeneration*9)},{m:"Feb",use:Math.round(d.currentConsumption*15),renew:Math.round(d.currentGeneration*10)},{m:"Mar",use:Math.round(d.currentConsumption*14),renew:Math.round(d.currentGeneration*11)},{m:"Apr",use:Math.round(d.currentConsumption*13),renew:Math.round(d.currentGeneration*11.5)},{m:"May",use:Math.round(d.currentConsumption*15),renew:Math.round(d.currentGeneration*10.5)},{m:"Jun",use:Math.round(d.currentConsumption*16),renew:Math.round(d.currentGeneration*10)}];return <Page title="Analytics" sub="Analytics recalculated from the latest station dataset."><div className="grid3"><div className="card"><div className="eyebrow">Renewable share</div><h2>{a.renewableShare.toFixed(1)}%</h2><p style={{color:"#8298a9",fontSize:12}}>Current generation relative to demand</p></div><div className="card"><div className="eyebrow">Peak demand</div><h2>{Math.round(a.consumption*1.22)} kW</h2><p style={{color:"#8298a9",fontSize:12}}>Projected peak from current profile</p></div><div className="card"><div className="eyebrow">Energy gap</div><h2>{a.gap} kW</h2><p style={{color:"#8298a9",fontSize:12}}>Current demand minus renewable output</p></div></div><div className="card" style={{marginTop:16}}><div className="card-title"><h3>Consumption and renewable contribution</h3></div><ResponsiveContainer width="100%" height={330}><BarChart data={monthly}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="m"/><YAxis/><Tooltip/><Legend/><Bar dataKey="use" fill="#69e7f5" name="Consumption (kWh)"/><Bar dataKey="renew" fill="#54d89b" name="Renewable (kWh)"/></BarChart></ResponsiveContainer></div></Page>}

function Reports({d,a}){const rows=[["Current generation",`${a.generation} kW`,a.gap?"Review":"Stable"],["Current consumption",`${a.consumption} kW`,`Live input`],["Renewable contribution",`${a.renewableShare.toFixed(1)}%`,`Calculated`],["Battery reserve",`${d.batterySoc}%`,`Healthy`],["Backup fuel",`${a.fuelPct.toFixed(0)}%`,`Calculated`],["Forecast gap",`${Math.max(0,d.forecastDemand-d.forecastRenewable)} kWh/day`,`Modelled`]];return <Page title="Reports" sub="Operational summaries generated from the latest submitted station data."><div className="card"><div className="card-title"><div><h3>Station energy report</h3><p>{d.stationName} • Latest analysis</p></div><button className="btn small" onClick={()=>window.print()}>Print / Save PDF</button></div><table className="table"><thead><tr><th>Metric</th><th>Value</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td>{r[0]}</td><td>{r[1]}</td><td className={r[2]==="Review"?"warning":"positive"}>{r[2]}</td></tr>)}</tbody></table></div><div className="grid2" style={{marginTop:16}}><div className="card"><h3 style={{fontSize:14}}>Executive summary</h3><p style={{fontSize:12,color:"#8fa5b6",lineHeight:1.7}}>{a.gap?`The submitted station data shows a ${a.gap} kW current energy gap. Backup planning and flexible-load scheduling should be reviewed against the forecast.`:`The submitted station data shows a positive current energy balance. Storage and flexible-load scheduling can absorb available renewable surplus.`}</p></div><div className="card"><h3 style={{fontSize:14}}>Data note</h3><p style={{fontSize:12,color:"#8fa5b6",lineHeight:1.7}}>This prototype uses manually entered or demo values. Connect validated station telemetry before using the system for operational decisions.</p></div></div></Page>}

function Page({title,sub,children}){return <div><div className="page-title"><div><div className="eyebrow">PolarGrid workspace</div><h1>{title}</h1><p>{sub}</p></div></div>{children}</div>}

function App(){
 const [view,setView]=useState("landing"),[page,setPage]=useState("dashboard"),[role,setRole]=useState("manager"),[sideOpen,setSideOpen]=useState(false),[stationData,setStationData]=useState(DEMO_STATION);
 const analysis=useMemo(()=>derive(stationData),[stationData]);
 const login=email=>{setRole(email.startsWith("admin")?"admin":email.startsWith("operations")?"operations":"manager");setView("app")};
 const runAnalysis=data=>{setStationData({...data,currentGeneration:Number(data.solarGeneration)+Number(data.windGeneration)});setPage("dashboard")};
 const resetDemo=()=>{setStationData(DEMO_STATION);setPage("dashboard")};
 if(view==="landing") return <Landing onLogin={()=>setView("login")}/>;
 if(view==="login") return <Login onLogin={login} onBack={()=>setView("landing")}/>;
 const content={data:<StationData data={stationData} onRun={runAnalysis} onDemo={resetDemo}/>,dashboard:<DashboardHome d={stationData} a={analysis}/>,monitoring:<Monitoring d={stationData} a={analysis}/>,forecast:<Forecast d={stationData} a={analysis}/>,renewable:<Renewable d={stationData} a={analysis}/>,storage:<Storage d={stationData} a={analysis}/>,fuel:<FuelOptimization d={stationData} a={analysis}/>,recommendations:<RecommendationsPage d={stationData} a={analysis}/>,alerts:<AlertsPage d={stationData} a={analysis}/>,simulation:<Simulation d={stationData} a={analysis}/>,analytics:<Analytics d={stationData} a={analysis}/>,reports:<Reports d={stationData} a={analysis}/>}[page]||<DashboardHome d={stationData} a={analysis}/>;
 return <div className="shell"><Sidebar page={page} setPage={setPage} open={sideOpen} setOpen={setSideOpen} onLogout={()=>setView("landing")}/><main className="main"><div className="dash-top"><div style={{display:"flex",alignItems:"center",gap:10}}><button className="menu-btn" onClick={()=>setSideOpen(true)}><Menu size={18}/></button><span style={{fontSize:12,color:"#7890a2"}}>{stationData.stationName}</span></div><div className="user-pill"><span>{role==="admin"?"Administrator":role==="operations"?"Operations Personnel":"Station Energy Manager"}</span><div className="avatar"><User size={15}/></div></div></div><div className="dashboard">{content}</div></main></div>
}

createRoot(document.getElementById("root")).render(<App/>);
